volumes:
    cowsdb_data: {}

services:

  cowsdb-server:
    image: ghcr.io/cowsdb/cowsdb:latest
    container_name: cowsdb-server
    restart: unless-stopped
    expose:
      - 8123
      - 9000
    volumes:
      - cowsdb_data:/app/.chdb_data
    environment:
      - PORT=8123
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 500M

  gigapipe:
    image: ghcr.io/metrico/gigapipe:latest
    container_name: qryn-cowsdb
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=cowsdb-server
      - CLICKHOUSE_AUTH="qryn:demo"
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_DB=qryn
    depends_on:
       - cowsdb-server
